name: Update screenshot of website

on:
  push:
    branches:
    - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for Vercel build
      run: sleep 300s
    - name: POST to screenshot service
      # You may pin to the exact commit or the version.
      # uses: muinmomin/webhook-action@7c067ef19e5de3aca7aebda32628f1d08d06bf89
      uses: muinmomin/webhook-action@v1.0.0
      with:
        # URL of webhook to send post request to
        url: "screenshot.jtlabs.co/api/screenshot"
        # JSON string of data to pass into request
        data: "{'url': 'https://officialjoshuataylor.com','size': ['1920x1080'],'fullPage': true,'darkMode': false,'format': 'png','delay': '3','width': 1920,'height': 1080,'scale': 1,'save': true,'pdf': {    'format': 'resolution',    'landscape': false},'script': '','style': '','urls': [    {        'url': null    }],'keepUrlStructure': false,'type': 'img','mimeType': 'image/png','password': null}"
